### ISSUE TITLE
What is site and SITE_TD meaning in this code? And how to define the label in the .csv file?

### ISSUE THREAD

**Issue by harveybi** [sk1712/gcn_metric_learning#1]
![problem](https://user-images.githubusercontent.com/38922463/40730366-117130ca-6461-11e8-9231-d993a4577f32.PNG)

**Comment by swg209** [comment]
@harveybi @sk1712    Does  the  ho_coords.csv  contains  dataset info ? Or say it is the dataset?

**Comment by sk1712** [comment]
@swg209 the ho_coords.csv file only contains the coordinates of the brain regions, as these are defined by the corresponding parcellation. It doesn't contain any more information about the dataset. Any further information about the dataset can be found here https://nilearn.github.io/modules/generated/nilearn.datasets.fetch_abide_pcp.html.
