### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/vol/dhcp-hcp-data/ABIDE/ABIDE_pcp/cpac/filt_noglobal/subject_IDs.txt'

### ISSUE THREAD

**Issue by LeeJunHyun** [sk1712/gcn_metric_learning#2]
FileNotFoundError: [Errno 2] No such file or directory: '/vol/dhcp-hcp-data/ABIDE/ABIDE_pcp/cpac/filt_noglobal/subject_IDs.txt'

Hi, thank you for sharing your code and data.

@sk1712 , How can I get `subject_IDs.txt`?
Can you provide this file?

**Comment by sk1712** [comment]
You will get this file when you download the dataset through nilearn https://nilearn.github.io/modules/generated/nilearn.datasets.fetch_abide_pcp.html

**Comment by rachelyou** [comment]
I have downloaded the dataset through nilearn, but the dataset did not include the subject_IDs.txt. Can you   provide the code?

**Comment by rachelyou** [comment]
I have downloaded the dataset through nilearn, but the dataset did not include the subject_IDs.txt. Can you provide the code?
@sk1712

**Comment by FengGao92** [comment]
> I have downloaded the dataset through nilearn, but the dataset did not include the subject_IDs.txt. Can you provide the code?
> @sk1712

I think you can find the subject_ID in the Phenotypic_V1_0b_preprocessed1.csv file which comes with the downloaded dataset. But this is just my understanding from the codes.

**Comment by FengGao92** [comment]
> I have downloaded the dataset through nilearn, but the dataset did not include the subject_IDs.txt. Can you provide the code?
> @sk1712

However, it seems the author directly read in the network data from matlab files, I was wondering if you figured out how to get that? Thanks!

**Comment by saiprasanna06** [comment]
> I have downloaded the dataset through nilearn, but the dataset did not include the subject_IDs.txt. Can you provide the code? @sk1712

Hi, were you able to solve this issue ? I am on the same boat.

**Comment by AstonshisL** [comment]
> 

Same here.Have you solved the problem?
